import { Theme, makeStyles } from '@material-ui/core/styles';

const usePeriodAnalysisSectionStyles = makeStyles((theme: Theme) => ({
  root: {
    flexGrow: 1,
    padding: theme.spacing(6),
  },
  mainTitle: {
    color: theme.palette.text.primary,
    letterSpacing: '-1.2px',
    textAlign: 'left',
    lineHeight: 1.33,
    fontWeight: 500,
    fontSize: '30px',
    fontFamily: 'AppleSDGothicNeo',
    marginBottom: theme.spacing(5),
  },
  infoText: {
    color: theme.palette.text.secondary,
    fontFamily: 'AppleSDGothicNeo',
    fontSize: '18px',
    lineHeight: '1.11',
    textAlign: 'right',
    marginRight: '110px',
  },
  mainBody: {
    color: theme.palette.text.secondary,
    letterSpacing: 'normal',
    textAlign: 'left',
    lineHeight: 1.5,
    fontSize: '22px',
    marginBottom: theme.spacing(4),
  },
  bodyPapper: {
    borderRadius: '12px',
    border: `solid 1px ${theme.palette.divider}`,
    backgroundColor: theme.palette.background.paper,
    width: '276px',
    height: '75px',
    paddingTop: theme.spacing(3),
    paddingBottom: theme.spacing(2),
    boxShadow: '0',
  },
  subTitle: {
    color: theme.palette.text.secondary,
    letterSpacing: 'normal',
    textAlign: 'left',
    lineHeight: 1.5,
    fontSize: '22px',
    fontFamily: 'AppleSDGothicNeo',
    marginLeft: theme.spacing(5),
    display: 'flex',
    alignItems: 'center',
  },
  bodyWrapper: {
    borderRadius: '12px',
    hegith: '292px',
    border: `solid 1px ${theme.palette.divider}`,
    backgroundColor: theme.palette.background.paper,
    paddingTop: theme.spacing(3),
    paddingBottom: theme.spacing(3),
    paddingRight: 0,
    marginRight: theme.spacing(5),
  },
  bodyTitle: {
    color: theme.palette.text.secondary,
    letterSpacing: 'normal',
    textAlign: 'left',
    lineHeight: 1.5,
    fontSize: '17px',
    fontFamily: 'AppleSDGothicNeo',
    marginLeft: theme.spacing(5),
    display: 'flex',
    marginBottom: theme.spacing(1),
  },
  anlaysisButton: {
    width: '136.2px',
    height: '51.1px',
    borderRadius: '6px',
    backgroundColor: theme.palette.primary.dark,
    fontFamily: 'AppleSDGothicNeo',
    fontSize: '24px',
    marginTop: theme.spacing(3),
    marginRight: theme.spacing(10),
    color: theme.palette.common.white,
    '&:hover': {
      backgroundColor: theme.palette.primary.light,
    },
  },
  alert: {
    borderRadius: '5px',
    marginBottom: theme.spacing(2),
    paddingTop: theme.spacing(1),
  },
}));

export default usePeriodAnalysisSectionStyles;
