name: Dev PR Checks - "server"

on:
  pull_request:
    branches: [master, dev]
    paths:
      - "server/**"

jobs:
  dev-pr-checks-server:
    name: dev-pr-checks-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Nodejs
        uses: actions/setup-node@v1

      - name: Lint Nest application
        id: lint
        run: |
          cd server
          yarn
          yarn lint
        env:
          CI: true

      - name: Create failure comment
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            [**ESLint Failed**]
            Check your code on your local environment  
            `server` 폴더에서 `yarn lint`를 통해 eslint 검사를 실행하고  
            규칙에 맞지 않는 부분을 확인하세요.

            [ESlint 로그 확인](https://github.com/whileTrueDev/tp-mvp/runs/1207840952?check_suite_focus=true)
            ${{ github.repository }}/actions/runs/${{ github.run_id }}
          reactions: "+1"
