name: Dev PR Checks - "server"

on:
  pull_request:
    branches: [master, dev]
    paths:
      - "server/**"

jobs:
  dev-pr-checks-server:
    name: dev-pr-checks-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Nodejs
        uses: actions/setup-node@v1

      - name: Lint Nest application
        run: |
          cd server
          yarn
          result=`yarn lint`
          echo "::set-output name=result::$result"
        env:
          CI: true

      - name: Create Comment
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 24
          body: |
            ### ESlint log
            ${{ steps.lint.outputs.result }}
          reactions: "+1"
