name: PR Checks - "client/admin"

on:
  pull_request:
    paths:
      - "client/admin/**"

jobs:
  PRcheck:
    name: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Nodejs
        uses: actions/setup-node@v1

      - name: Install dependencies
        uses: bahmutov/npm-install@v1 # install dependencies using cache

      - name: Lint Check React App - client/admin
        id: lint
        run: |
          cd client/admin
          yarn lint
        env:
          CI: true

      - name: Build Check React App - client/admin
        id: build
        run: |
          cd client/admin
          yarn build
        env:
          CI: true

      - name: Create lint check failure comment
        if: ${{ steps.lint.outcome == 'failure' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            [**ESLint Failed**]
            Check your code on your local environment.  
            코드 편집 도구로 돌아가, `client/admin` 폴더에서 `yarn lint`를 통해 eslint 검사를 실행하고  
            규칙에 맞지 않는 부분을 확인하세요.

            [Github Actions 탭에서 ESlint 로그 확인하기](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          reactions: "+1"

      - name: Create build check failure comment
        if: ${{ steps.build.outcome == 'failure' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            [**Build Failed**]
            Check your code on your local environment.  
            모듈 빌드에 실패했습니다.
            코드 편집 도구로 돌아가, `client/admin` 폴더에서 `yarn build`를 통해 모듈 빌드를 실행하여 오류를 확인하세요.  

            [Github Actions 탭에서 Build 로그 확인하기](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          reactions: "+1"
