on:
  push:
    branches: [test]

name: Test deploy to AWS ECS - "server"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      #  Install All Dependencies
      - name: Install dependencies
        uses: bahmutov/npm-install@v1 # install dependencies using cache

      #  Build Shared Module
      - name: Build shared module
        id: shared-build
        run: |
          cd shared
          yarn build

      #  Build API server
      - name: TS Build
        run: |
          cd server
          yarn build

      - name: Build, tag, and push image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@2.14
        env:
          NODE_ENV: test
        with:
          dockerfile: server/test.Dockerfile
          name: ${{ secrets.DOCKER_USERNAME }}/test-truepoint-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ github.sha }},latest"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: server/test-task-definition.json
          container-name: test-truepoint-api-container
          image: ${{ secrets.DOCKER_USERNAME }}/test-truepoint-api:${{ github.sha }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE_NAME_API_SERVER_TEST_ENV }}
          cluster: ${{ secrets.ECS_CLUSTER_NAME_TEST_ENV }}
          wait-for-service-stability: true
